pool:
  vmImage: 'ubuntu-16.04'
steps:
  - script: npm ci
    displayName: Npm Install
  - script: npm run build
    displayName: Build
  - script: npm test
    displayName: Test
  - script: ./cypress-test.sh
    displayName: e2e cypress testing
